### ISSUE TITLE
AppDef config option

### ISSUE THREAD

**Issue by ggwpez** [perun-network/perun-eth-demo#21]
Add an option to the config `*.yaml` files `channel.AppDef` which defines the App Definition (ethereum Address).

**Comment by matthiasgeihs** [comment]
we discussed this offline. the rootSeed message is caused by package wire/net importing pkg/test and would not be surpressed by defining an appdef. assigning back to you.

**Comment by ggwpez** [comment]
I updated the issue to only reflect the `AppDef` config change, since the `root seed` message must be fixed in *go-perun* see https://git.perun.network/perun/go-perun/-/issues/222

**Comment by ggwpez** [comment]
Our payment app has a unique address now and does not need an on-chain address. Closing.
