### ISSUE TITLE
Use UpdateBy in paymentChannel updates

### ISSUE THREAD

**Issue by sebastianst** [perun-network/perun-eth-demo#6]
Introduces in go-perun with commit 9c54cb60867425edc49ffa1e25db6cd5b5345794

**Comment by ggwpez** [comment]
Depends on if that makes it incompatible with the *prnm*. Otherwise i would wait for *Charon*.

**Comment by ggwpez** [comment]
Looks like https://github.com/perun-network/perun-eth-demo/pull/25/commits/ea6db1ae3a17abe3d59040b0e6443333881e111b already did this.
