### ISSUE TITLE
Charon update; enable LevelDB persistence

### ISSUE THREAD

**Issue by sebastianst** [perun-network/perun-eth-demo#9]
We should update the demo's go-perun to Charon and also enable persistence (using leveldb) to showcase how it works in practice. Would also deliver an additional good test of our persistence impl.

I propose that we add an additional `persistence` section to the configuration with a `dbpath` for the path to the leveldb file and possible additional settings relevant for the leveldb persistence backend.

Could also additionally expose this as a cmdline flag `dbpath`.

What to you think @ggwpez?

**Comment by ggwpez** [comment]
Yea `dbPath` or `storagePath` sound good. I will start with this and then do the *prnm* afterwards, since it is easier to debug in the node.
